apiVersion: v2
name: pihole
description: Pi-hole v6 Helm Chart with full FTL configuration support.
icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
type: application
maintainers:
  - name: Nuno Fernandes
    email: nuno.o.fernandes@outlook.pt
    url: https://nunoferna.github.io
version: 0.4.3
appVersion: "2026.02.0"
kubeVersion: ">=1.23.0"
home: https://nunoferna.github.io/pihole-helm/
keywords:
  - pihole
  - dns
  - adblock
  - dhcp
  - monitoring
sources:
  - https://github.com/nunoferna/pihole-helm
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/nunoferna/pihole-helm
    - name: Upstream Docker Project
      url: https://github.com/pi-hole/docker-pi-hole
    - name: Upstream Pi-hole Project
      url: https://github.com/pi-hole/pi-hole
    - name: Pi-hole Exporter
      url: https://github.com/eko/pihole-exporter
