apiVersion: v2
name: pihole
description: Enterprise-grade Pi-hole v6 Helm Chart with full FTL configuration support.
type: application
version: 0.2.2
appVersion: "2025.11.1"
kubeVersion: ">=1.23.0"
keywords:
  - pihole
  - dns
  - adblock
  - dhcp
  - monitoring
home: https://nunoferna.github.io/pihole-helm/
icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
sources:
  - https://github.com/pi-hole/docker-pi-hole
maintainers:
  - name: Nuno Fernandes
    email: nuno.o.fernandes@outlook.pt
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: pihole
      image: pihole/pihole:2025.11.1
    - name: pihole-exporter
      image: ekofr/pihole-exporter:v1.2.0
