apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}-lists
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
  import-lists.sh: |-
{{ .Files.Get "files/import-lists.sh" | indent 4 }}