{{- if .Values.metrics.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pihole.metricsSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pihole.metricsSelectorLabels" . | nindent 8 }}
  {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
    spec:
  {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "pihole.fullname" .) | quote }}
      containers:
        - name: metrics
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
  {{- with .Values.metrics.command }}
          command:
            {{- toYaml . | nindent 12 }}
  {{- end }}
  {{- with .Values.metrics.args }}
          args:
            {{- toYaml . | nindent 12 }}
  {{- end }}
          env:
  {{- $userEnvKeys := dict }}
  {{- range .Values.metrics.env }}
    {{- $_ := set $userEnvKeys .name true }}
  {{- end }}
  {{- if not (hasKey $userEnvKeys "PIHOLE_HOSTNAME") }}
            - name: PIHOLE_HOSTNAME
              value: {{ include "pihole.metricsHostnames" . | quote }}
  {{- end }}
  {{- if not (hasKey $userEnvKeys "PIHOLE_PORT") }}
            - name: PIHOLE_PORT
              value: {{ include "pihole.metricsPorts" . | quote }}
  {{- end }}
  {{- if not (hasKey $userEnvKeys "PIHOLE_PROTOCOL") }}
            - name: PIHOLE_PROTOCOL
              value: {{ include "pihole.metricsProtocols" . | quote }}
  {{- end }}
  {{- range .Values.metrics.env }}
            - name: {{ .name }}
              {{- omit . "name" | toYaml | nindent 14 }}
  {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
{{- end }}
