{{- if and (not (include "pihole.isStatefulSet" .)) .Values.persistence.etcPihole.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pihole.fullname" . }}-etc-pihole
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.etcPihole.accessMode }}
  {{- if .Values.persistence.etcPihole.storageClassName }}
  storageClassName: {{ .Values.persistence.etcPihole.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.etcPihole.size }}
{{- end }}
{{- if and (not (include "pihole.isStatefulSet" .)) .Values.persistence.etcDnsmasq.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pihole.fullname" . }}-etc-dnsmasq
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.etcDnsmasq.accessMode }}
  {{- if .Values.persistence.etcDnsmasq.storageClassName }}
  storageClassName: {{ .Values.persistence.etcDnsmasq.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.etcDnsmasq.size }}
{{- end }}
