{{- if and (not .Values.pihole.web.existingSecret) (not .Values.pihole.web.skipPasswordEnv) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}-web-password
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.pihole.web.password }}
  {{ .Values.pihole.web.passwordSecretKey }}: {{ .Values.pihole.web.password | b64enc | quote }}
  {{- else }}
  {{ .Values.pihole.web.passwordSecretKey }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}