{{- if .Values.serviceWeb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-web
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceWeb.annotations | nindent 4 }}
spec:
  type: {{ .Values.serviceWeb.type }}
  {{- if or (eq .Values.serviceWeb.type "LoadBalancer") (eq .Values.serviceWeb.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.serviceWeb.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.serviceWeb.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.serviceWeb.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.serviceWeb.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.serviceWeb.type "NodePort") .Values.serviceWeb.nodePorts.http }}
      nodePort: {{ .Values.serviceWeb.nodePorts.http }}
      {{- end }}
    - port: {{ .Values.serviceWeb.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
      {{- if and (eq .Values.serviceWeb.type "NodePort") .Values.serviceWeb.nodePorts.https }}
      nodePort: {{ .Values.serviceWeb.nodePorts.https }}
      {{- end }}
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
{{- end }}