{{- if .Values.pihole.ftl.ntp.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-ntp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.pihole.ftl.ntp.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.pihole.ftl.ntp.service.type }}
  {{- if or (eq .Values.pihole.ftl.ntp.service.type "LoadBalancer") (eq .Values.pihole.ftl.ntp.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.pihole.ftl.ntp.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.pihole.ftl.ntp.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.pihole.ftl.ntp.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.pihole.ftl.ntp.service.ports.ntp }}
      targetPort: ntp
      protocol: UDP
      name: ntp
  {{- if and (eq .Values.pihole.ftl.ntp.service.type "NodePort") .Values.pihole.ftl.ntp.service.nodePort }}
      nodePort: {{ .Values.pihole.ftl.ntp.service.nodePort }}
  {{- end }}
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
{{- end }} 
