name: Trivy IaC Scanner

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  schedule:
    - cron: '0 4 * * 1' # Runs automatically every Monday at 4 AM

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Scan Helm Chart for Misconfigurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_HELM_KUBE_VERSION: "v1.35.1"
        with:
          scan-type: 'config'
          scan-ref: 'charts/pihole'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'helm-misconfigurations'
