name: Trivy IaC Scanner

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  schedule:
    - cron: '0 4 * * 1' # Runs automatically every Monday at 4 AM

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Scan Helm Chart for Misconfigurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@97e0b3872f55f89b95b2f65b3dbab56962816478 # v0.34.2
        env:
          TRIVY_HELM_KUBE_VERSION: "v1.35.1"
        with:
          scan-type: 'config'
          scan-ref: 'charts/pihole'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'helm-misconfigurations'
