name: Trivy IaC Scanner

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'charts/**'
  schedule:
    - cron: '0 4 * * 1' # Runs automatically every Monday at 4 AM

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Scan Helm Chart for Misconfigurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'charts/pihole'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@89a39a4e59826350b863aa6b6252a07ad50cf83e # v4
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'helm-misconfigurations'